version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/blog-vanilla
    overwrite: yes

permissions:
  - object: /home/ubuntu
    pattern: '**'
    owner: ubuntu
    group: ubuntu

hooks:
  BeforeInstall:
    - location: scripts/before-deploy.sh
      runas: ubuntu
  AfterInstall:
    - location: scripts/after-deploy.sh
      runas: ubuntu
